<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CP1.Core\CP1.Core.csproj" />
    <ProjectReference Include="..\CP1.Data\CP1.Data.csproj" />
    <ProjectReference Include="..\CP1.Models\CP1.Models.csproj" />
  </ItemGroup>

</Project>
